name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "extractor"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
# Using v4.24.0 to match the Lean version
rev = "v4.24.0"
